# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy Azure Resources and Application
# See readme file for info about the contents of the variable group
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest
trigger:
  # since this repo has both AzDO and GHA pipelines, nothing is run automatically...
  - none
  # batch: true
  # branches:
  #   include:
  #     - main
  #   exclude:
  #     - '**/*.md'
  # paths:
  #   include:
  #     - 'src/Dadabase.web/**'

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: deployToEnvironment
    displayName: Deploy To
    type: string
    values:
      - DEV
      - QA
      - PROD
      - DEV-QA-PROD
    default: DEV
  - name: deployBicep
    displayName: Deploy Bicep
    type: boolean
    default: false
  - name: runUnitTests
    displayName: Run Unit Tests
    type: boolean
    default: true
  - name: runSmokeTest
    displayName: Run Playwright Smoke Test
    type: boolean
    default: true
  - name: runMSDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: true
  - name: runGHASScan
    displayName: Run GHAS Scan
    type: boolean
    default: false

# ----------------------------------------------------------------------------------------------------
variables:
  - group: Dadabase.Demo
  - template: vars/var-service-connections.yml

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if ne(parameters.deployToEnvironment, 'DEV-QA-PROD') }}:
  - template: pipes/infra-and-webapp-pipe.yml
    parameters:
      environments: ['${{ parameters.deployToEnvironment }}']
      deployBicep: ${{ parameters.deployBicep }}
      parseBicepOutputs: true
      runSmokeTest: ${{ parameters.runSmokeTest }}
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
      runGHASScan: ${{ parameters.runGHASScan }}
      runUnitTests: ${{ parameters.runUnitTests }}

- ${{ if eq(parameters.deployToEnvironment, 'DEV-QA-PROD') }}:
  - template: pipes/infra-and-webapp-pipe.yml
    parameters:
      environments: ['DEV','QA','PROD']
      deployBicep: ${{ parameters.deployBicep }}
      parseBicepOutputs: true
      runSmokeTest: ${{ parameters.runSmokeTest }}
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
      runGHASScan: ${{ parameters.runGHASScan }}
      runUnitTests: ${{ parameters.runUnitTests }}
