# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to Run Security Scan
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger:
 - none

schedules:
- cron: '0 12 * * 3'
  displayName: Scan Every Wednesday
  branches:
    include:
    - main

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: runMSDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: true
  - name: runGHASScan
    displayName: Run GHAS Scan
    type: boolean
    default: false

# ----------------------------------------------------------------------------------------------------
variables:
  - group: Dadabase.Demo
  - template: vars/var-service-connections.yml

# ----------------------------------------------------------------------------------------------------
stages:
- template: pipes/scan-code-pipe.yml
  parameters:
    runGHASScan: ${{ parameters.runGHASScan }}
    runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
