# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to Run Dependabot 
# https://learn.microsoft.com/en-us/azure/security/container-secure-supply-chain/articles/container-secure-supply-chain-implementation/cssc-depenadabot
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

schedules:
- cron: '0 3 * * 3'
  displayName: Scan Every Wednesday
  branches:
    include:
    - main

jobs:
- job:
  steps:
  - script: |
      git clone https://github.com/dependabot/dependabot-core.git
      cd dependabot-core

      DOCKER_BUILDKIT=1 docker build \
        --build-arg "USER_UID=$(id -u)" \
        --build-arg "USER_GID=$(id -g)" \
        -t "dependabot/dependabot-core" .
      cd ..
    displayName: build dependabot-core Docker image

  - script: |
      git clone https://github.com/dependabot/dependabot-script.git
      cd dependabot-script

      docker run -v "$(pwd):/home/dependabot/dependabot-script" -w /home/dependabot/dependabot-script dependabot/dependabot-core bundle install -j 3 --path vendor
    displayName: install dependencies

  - script: |
      #!/bin/bash
      SYSTEM_COLLECTIONURI_TRIM=`echo "${SYSTEM_COLLECTIONURI:22}"`
      PROJECT_PATH="$SYSTEM_COLLECTIONURI_TRIM$SYSTEM_TEAMPROJECT/_git/$BUILD_REPOSITORY_NAME"
      echo "path: $PROJECT_PATH"

      docker run  -v "$(pwd)/dependabot-script:/home/dependabot/dependabot-script" \
                  -w '/home/dependabot/dependabot-script' \
                  -e AZURE_ACCESS_TOKEN=$(System.AccessToken) \
                  -e PACKAGE_MANAGER=docker \
                  -e PROJECT_PATH=$PROJECT_PATH \
                  -e DIRECTORY_PATH=/ \
                  -e OPTIONS="$OPTIONS" \
                  dependabot/dependabot-core bundle exec ruby ./generic-update-script.rb
    displayName: "run dependabot"
    env:
      OPTIONS: |
        { "kubernetes_updates": true }