FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["DadJokeMCPStdIO/DadJokeMCPStdIO.csproj", "DadJokeMCPStdIO/"]
COPY ["DadJokeMCP.Shared/DadJokeMCP.Shared.csproj", "DadJokeMCP.Shared/"]
RUN dotnet restore "DadJokeMCPStdIO/DadJokeMCPStdIO.csproj"

COPY . .
WORKDIR "/src/DadJokeMCPStdIO"
RUN dotnet publish "DadJokeMCPStdIO.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/runtime:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "DadJokeMCPStdIO.dll"]